version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: DB_PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/tables/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    container_name: DB_PGAdmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8001
    ports:
      - "8001:8001"
    depends_on:
      - postgres

  angular:
    container_name: Angular
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local