version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_projeto_angular
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2003
      POSTGRES_DB: projetoAngular
    ports:
      - "8080:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
